name: argocd deploy
on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      env:
        type: string
        required: true

jobs:
  argocd-dev-deploy:
    runs-on: ["self-hosted"]
    steps:
      - name: get-bootstrap
        run: |
          aws eks update-kubeconfig --name ${{ inputs.env }}-eks

      - name: code-checkout
        uses: actions/checkout@v4

      - name: argocd ${{ inputs.component }} deploy
        run: |
          kubectl apply -f argocd/${{ inputs.component }}.yaml
