name: continuous-integration
on:
  workflow_call:
    inputs:
      component_name:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  ci:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: git-clone
        run: |
          echo "Sample workflow ${{ inputs.component_name }} - Secrets- ${{ secrets.token }}"
          
          
