name: continuous-integration
on:
  workflow_call:
    inputs:
      component_name:
        type: string
        required: true
      docker_build:
        type: string
        required: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: git-clone
        run: |
          printenv