name: Building Docker Images For Roboshop
on:
  workflow_call:
    inputs:
      component_name:
        type: string
jobs:
  docker-ci:
    runs-on: [self-hosted]
    env:
      docker_username: ${{ secrets.docker_username }}
      docker_password: ${{ secrets.docker_password }}
    steps:
      - name: docker login
        run: |
          docker login -u ${docker_username} -p ${docker_password}
          
          
