name: Building Docker Images For Roboshop
on:
  workflow_call:
    inputs:
      image_name:
        type: string
jobs:
  docker-ci:
    runs-on: [self-hosted]
    env:
      docker_username: ${{ secrets.docker_username }}
      docker_password: ${{ secrets.docker_password }}
      image_name: ${{ inputs.image_name }}
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: docker login
        run: |
          docker login -u ${docker_username} -p ${docker_password}

      - name: docker build
        run: |
           docker build -t ${{ secrets.docker_username }}/$(echo ${image_name#*/}) .
        env:


      - name: docker push
        run: |
          echo docker push ${{ secrets.docker_username }}/$(echo ${image_name#*/})

      - name: clean up space
        run: |
          docker rmi -f ${{ secrets.docker_username }}/$(echo ${image_name#*/})



          
          
